# Generated by Django 4.1.5 on 2023-01-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type_of_product", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("location", models.CharField(max_length=100)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "Higher Quality"),
                            ("B", "Good Quality"),
                            ("C", "Lower Quality"),
                        ],
                        max_length=1,
                    ),
                ),
                ("seasonality", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="products_images/")),
            ],
        ),
    ]
